<a href="https://colab.research.google.com/github/2303A51689/PDS_LAB-batch-10/blob/main/PDS_Lab_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

marks = np.array([
    [85, 78, 92],
    [70, 88, 76],
    [90, 95, 89],
    [65, 60, 72],
    [88, 82, 91]
])

print("Marks:\n", marks)
print("Average:", np.mean(marks, axis=1))
print("Minimum:", np.min(marks, axis=1))
print("Maximum:", np.max(marks, axis=1))

print("Student 3 Marks:", marks[2])
print("Students scoring >80:")
for i, row in enumerate(marks):
    if np.any(row > 80):
        print(" Student", i+1, row)

print("Subject-wise performance:\n", marks.T)


Marks:
 [[85 78 92]
 [70 88 76]
 [90 95 89]
 [65 60 72]
 [88 82 91]]
Average: [85.         78.         91.33333333 65.66666667 87.        ]
Minimum: [78 70 89 60 82]
Maximum: [92 88 95 72 91]
Student 3 Marks: [90 95 89]
Students scoring >80:
 Student 1 [85 78 92]
 Student 2 [70 88 76]
 Student 3 [90 95 89]
 Student 5 [88 82 91]
Subject-wise performance:
 [[85 70 90 65 88]
 [78 88 95 60 82]
 [92 76 89 72 91]]


In [8]:
import pandas as pd

data = {
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department": ["HR", "IT", "Finance", "Marketing", "IT"],
    "Salary": [48000, 52000, 75000, 46000, 90000]
}
df = pd.DataFrame(data)
print("Original Data:\n", df)

# Filter salary > 50,000
print("\nEmployees with Salary > 50,000:\n", df[df["Salary"] > 50000])

# Sort by salary (descending)
df_sorted = df.sort_values(by="Salary", ascending=False)
print("\nSorted by Salary (desc):\n", df_sorted)

# Add Bonus (10% of salary)
df["Bonus"] = df["Salary"] * 0.10
print("\nWith Bonus Column:\n", df)

# Total expense (Salary + Bonus)
df["Total"] = df["Salary"] + df["Bonus"]
print("\nTotal Salary Expense including Bonus:", df["Total"].sum())

# Save to CSV
df.to_csv("employee_salary_analysis.csv", index=False)
print("\nData saved to 'employee_salary_analysis.csv'")

Original Data:
     ID     Name Department  Salary
0  101    Alice         HR   48000
1  102      Bob         IT   52000
2  103  Charlie    Finance   75000
3  104    David  Marketing   46000
4  105      Eva         IT   90000

Employees with Salary > 50,000:
     ID     Name Department  Salary
1  102      Bob         IT   52000
2  103  Charlie    Finance   75000
4  105      Eva         IT   90000

Sorted by Salary (desc):
     ID     Name Department  Salary
4  105      Eva         IT   90000
2  103  Charlie    Finance   75000
1  102      Bob         IT   52000
0  101    Alice         HR   48000
3  104    David  Marketing   46000

With Bonus Column:
     ID     Name Department  Salary   Bonus
0  101    Alice         HR   48000  4800.0
1  102      Bob         IT   52000  5200.0
2  103  Charlie    Finance   75000  7500.0
3  104    David  Marketing   46000  4600.0
4  105      Eva         IT   90000  9000.0

Total Salary Expense including Bonus: 342100.0

Data saved to 'employee_salary_anal